---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        neovim_version: ["nightly", "stable"]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install tools with UBI
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin"
          # make the tools available for subsequent steps
          echo "$(pwd)/bin" >> "$GITHUB_PATH"
          curl --silent --location \
              https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
              TARGET="$HOME/.local/bin" sh

          ubi --project mikefarah/yq

          VERSION=$(yq '.tools."github:BurntSushi/ripgrep".version' mise.toml)
          ubi --project BurntSushi/ripgrep --tag "$VERSION" --exe rg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lua tests
        uses: nvim-neorocks/nvim-busted-action@bbcfe82d35b8fb4660ef6ed4124e1fd9cef4688b # v1.2.0
        with:
          nvim_version: ${{ matrix.neovim_version }}
          luarocks_version: "3.11.1"

      # https://github.com/cypress-io/github-action?tab=readme-ov-file#pnpm-workspaces
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install

      # need to work around https://github.com/cypress-io/github-action/issues/1246
      - run: pnpm --filter integration-tests exec cypress install
      - name: Run end-to-end tests
        run: |
          rg --version
          pnpm tui run

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        # add the line below to store screenshots only on failures
        # if: failure()
        if: failure()
        with:
          name: cypress-screenshots
          path: integration-tests/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

